# Generated by Django 3.0.4 on 2020-03-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_name', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=50)),
                ('insight', models.TextField()),
                ('friendship', models.TextField()),
                ('love', models.TextField()),
                ('strengths', models.CharField(max_length=200)),
                ('weakness', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=200)),
                ('dislikes', models.CharField(max_length=200)),
                ('shade_of_insanity', models.CharField(max_length=200)),
                ('date_range', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horrorscopes.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('horror', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zodiac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horrorscopes.Zodiac')),
            ],
        ),
    ]
